spring.application.name=springboot-api-lambda

# Serverless Optimization
spring.main.banner-mode=off
spring.main.lazy-initialization=true
logging.level.root=INFO

# Database Tuning (Only if using a DB)
# High pool sizes are useless in Lambda because one Lambda = one concurrent request
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.idle-timeout=10000
